services:
  accident_clustering:
    build: .
    container_name: accident_clustering
    working_dir: /app
    volumes:
      - .:/app
    mem_limit: 32g
    shm_size: 2g
    command: jupyter execute large_scale_accident_clustering.ipynb